<template>
  <div class="col-lg-12">
    <table class="table table-condensed">
      <thead>
      <tr>
        <th v-for="(item,index) in classtitle">{{item}}</th>
      </tr>
      </thead>
      <tbody>
      <tr v-for="(item,index) in list">
        <th>{{item.id}}</th>
        <th>{{item.commodityName}}</th>
        <th>{{item.notes}}</th>
        <th>{{item.colour.colour1}}</th>
        <th>{{item.type.type1}}</th>
        <th>{{item.price}}</th>
        <th>{{item.number}}</th>
        <th>{{item.classification}}</th>
        <th>
          <el-button type="primary" style="padding: 0;"data-toggle="modal" data-target=".bs-example-modal-lg">修改</el-button>
          <el-button type="danger" style="padding: 0;">删除</el-button>
        </th>
      </tr>
      </tbody>
    </table>
  </div>
</template>

<script>

  export default {
    data(){
      return{
        classtitle:[
          '#',
          '商品名称',
          '介绍',
          '颜色',
          '款型',
          '价格',
          '数量',
          '分类',
          '操作',
        ],
        list:[
          /*
          *   id  商品名称  注释    数量    价格    所属分类  款型  颜色
          */
          {
            id:'001',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'002',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'003',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'004',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'006',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'007',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'009',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0010',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0011',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0012',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0013',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0014',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0015',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0016',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0018',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0019',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
          {
            id:'0020',
            commodityName:'画板咖啡几®－椭圆形',
            notes:'全实木手感，朴素与端庄的客厅之选',
            colour:{
              colour1:'白色',
              colour2:'胡桃木色',
              colour3:'木本色',
            },
            type:{
              type1:'椭圆形',
              type2:'胶囊型'
            },
            price:'1699',
            number:'100',
            classification:'书桌，餐桌',
          },
        ],
      }
    }
  }
</script>
